//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModForResearchTUB.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModForResearchTUB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this task you will follow the other transporter. ähnelt.
        /// </summary>
        internal static string convoy_intro_1 {
            get {
                return ResourceManager.GetString("convoy_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try to stay close to it! ähnelt.
        /// </summary>
        internal static string convoy_intro_2 {
            get {
                return ResourceManager.GetString("convoy_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A blue dot on the map shows its position. ähnelt.
        /// </summary>
        internal static string convoy_intro_3 {
            get {
                return ResourceManager.GetString("convoy_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this task you drive a motorcycle. ähnelt.
        /// </summary>
        internal static string desert_intro_1 {
            get {
                return ResourceManager.GetString("desert_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are 2 possible routes. ähnelt.
        /// </summary>
        internal static string desert_intro_2 {
            get {
                return ResourceManager.GetString("desert_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The normal route leads over roads and the highway ähnelt.
        /// </summary>
        internal static string desert_intro_3 {
            get {
                return ResourceManager.GetString("desert_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The alternative route leads through the desert. ähnelt.
        /// </summary>
        internal static string desert_intro_4 {
            get {
                return ResourceManager.GetString("desert_intro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The latter is marked by red checkpoints. ähnelt.
        /// </summary>
        internal static string desert_intro_5 {
            get {
                return ResourceManager.GetString("desert_intro_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GTA V is an open world action game. ähnelt.
        /// </summary>
        internal static string intro1 {
            get {
                return ResourceManager.GetString("intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This might result in hostile action from bystanders ... ähnelt.
        /// </summary>
        internal static string intro10 {
            get {
                return ResourceManager.GetString("intro10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or persecution by the police. ähnelt.
        /// </summary>
        internal static string intro11 {
            get {
                return ResourceManager.GetString("intro11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your wanted level is shown on the top right of the screen. ähnelt.
        /// </summary>
        internal static string intro12 {
            get {
                return ResourceManager.GetString("intro12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Higher wanted level = more police ähnelt.
        /// </summary>
        internal static string intro13 {
            get {
                return ResourceManager.GetString("intro13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collisions will damage your car. ähnelt.
        /// </summary>
        internal static string intro14 {
            get {
                return ResourceManager.GetString("intro14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the car&apos;s hitpoints drop to 0, it will explode. ähnelt.
        /// </summary>
        internal static string intro15 {
            get {
                return ResourceManager.GetString("intro15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the character&apos;s hitpoints drop to 0, he will fall unconscious. ähnelt.
        /// </summary>
        internal static string intro16 {
            get {
                return ResourceManager.GetString("intro16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The car is controlled with the steering wheel and gas/brake pedal. ähnelt.
        /// </summary>
        internal static string intro17 {
            get {
                return ResourceManager.GetString("intro17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no blinkers. Just turn. ähnelt.
        /// </summary>
        internal static string intro18 {
            get {
                return ResourceManager.GetString("intro18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To reverse, stand on the brake pedal after the car has stopped ähnelt.
        /// </summary>
        internal static string intro19 {
            get {
                return ResourceManager.GetString("intro19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This study focusses on the singleplayer mode of the game. ähnelt.
        /// </summary>
        internal static string intro2 {
            get {
                return ResourceManager.GetString("intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold the steering wheel turned to flip the car back over. ähnelt.
        /// </summary>
        internal static string intro20 {
            get {
                return ResourceManager.GetString("intro20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You now have 10min. to get familiar with the game. ähnelt.
        /// </summary>
        internal static string intro21 {
            get {
                return ResourceManager.GetString("intro21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can drive wherever you want. ähnelt.
        /// </summary>
        internal static string intro22 {
            get {
                return ResourceManager.GetString("intro22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To start immediately, drive through the checkpoints. ähnelt.
        /// </summary>
        internal static string intro23 {
            get {
                return ResourceManager.GetString("intro23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You control one of these three player characters. ähnelt.
        /// </summary>
        internal static string intro3 {
            get {
                return ResourceManager.GetString("intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All of the tasks revolve around a driving task. ähnelt.
        /// </summary>
        internal static string intro4 {
            get {
                return ResourceManager.GetString("intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will spend most of the time in a car. ähnelt.
        /// </summary>
        internal static string intro5 {
            get {
                return ResourceManager.GetString("intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive through these checkpoints. ähnelt.
        /// </summary>
        internal static string intro6 {
            get {
                return ResourceManager.GetString("intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The route is displayed on the minimap. ähnelt.
        /// </summary>
        internal static string intro7 {
            get {
                return ResourceManager.GetString("intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can either adhere to the traffic rules or ignore them. ähnelt.
        /// </summary>
        internal static string intro8 {
            get {
                return ResourceManager.GetString("intro8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is possible to run over pedestrians. ähnelt.
        /// </summary>
        internal static string intro9 {
            get {
                return ResourceManager.GetString("intro9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string menu_english {
            get {
                return ResourceManager.GetString("menu_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string menu_german {
            get {
                return ResourceManager.GetString("menu_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available languages ähnelt.
        /// </summary>
        internal static string menu_languages {
            get {
                return ResourceManager.GetString("menu_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This can&apos;t be done during tasks. ähnelt.
        /// </summary>
        internal static string menu_not_during_task {
            get {
                return ResourceManager.GetString("menu_not_during_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle debug mode? ähnelt.
        /// </summary>
        internal static string menu_toggle_debug {
            get {
                return ResourceManager.GetString("menu_toggle_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle route designer? ähnelt.
        /// </summary>
        internal static string menu_toggle_route_designer {
            get {
                return ResourceManager.GetString("menu_toggle_route_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All races are set up. ähnelt.
        /// </summary>
        internal static string racessetup {
            get {
                return ResourceManager.GetString("racessetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press [F10] to start first race ähnelt.
        /// </summary>
        internal static string startracepromp {
            get {
                return ResourceManager.GetString("startracepromp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The task has started! ähnelt.
        /// </summary>
        internal static string task_started {
            get {
                return ResourceManager.GetString("task_started", resourceCulture);
            }
        }
    }
}
