//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModForResearchTUB.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModForResearchTUB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The average speed of the player&apos;s vehicle (possibly in m/s) ähnelt.
        /// </summary>
        internal static string average_speed {
            get {
                return ResourceManager.GetString("average_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal received from brake pedal ähnelt.
        /// </summary>
        internal static string brake {
            get {
                return ResourceManager.GetString("brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long did the player apply the brakes before the garbage truck ähnelt.
        /// </summary>
        internal static string brake_in_front_of_garbage_truck {
            get {
                return ResourceManager.GetString("brake_in_front_of_garbage_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cam Designer active: {0} ähnelt.
        /// </summary>
        internal static string cam_designer_active {
            get {
                return ResourceManager.GetString("cam_designer_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use WASD, Up/Down, +/- and Numpad 7/9 to control cam ähnelt.
        /// </summary>
        internal static string cam_designer_cam_move {
            get {
                return ResourceManager.GetString("cam_designer_cam_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press X to toggle camera mode ähnelt.
        /// </summary>
        internal static string cam_designer_toggle {
            get {
                return ResourceManager.GetString("cam_designer_toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many hitpoints did the player&apos;s vehicle have after the task ähnelt.
        /// </summary>
        internal static string car_health {
            get {
                return ResourceManager.GetString("car_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Car vs. Car Initialization ähnelt.
        /// </summary>
        internal static string carvscar_initialization {
            get {
                return ResourceManager.GetString("carvscar_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For this task you choose between these two cars. ähnelt.
        /// </summary>
        internal static string carvscar_intro_1 {
            get {
                return ResourceManager.GetString("carvscar_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One is a race car, that is locked. ähnelt.
        /// </summary>
        internal static string carvscar_intro_2 {
            get {
                return ResourceManager.GetString("carvscar_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Its alarm will alert the police. ähnelt.
        /// </summary>
        internal static string carvscar_intro_3 {
            get {
                return ResourceManager.GetString("carvscar_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is faster, but more difficult to drive. ähnelt.
        /// </summary>
        internal static string carvscar_intro_4 {
            get {
                return ResourceManager.GetString("carvscar_intro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This regular car is unlocked. ähnelt.
        /// </summary>
        internal static string carvscar_intro_5 {
            get {
                return ResourceManager.GetString("carvscar_intro_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You won&apos;t get a wanted level, if you choose it. ähnelt.
        /// </summary>
        internal static string carvscar_intro_6 {
            get {
                return ResourceManager.GetString("carvscar_intro_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checkpoint {0}/{1} reached ähnelt.
        /// </summary>
        internal static string checkpoint_reached {
            get {
                return ResourceManager.GetString("checkpoint_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Convoy Task Initialization ähnelt.
        /// </summary>
        internal static string convoy_initialization {
            get {
                return ResourceManager.GetString("convoy_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this task you will follow the other transporter. ähnelt.
        /// </summary>
        internal static string convoy_intro_1 {
            get {
                return ResourceManager.GetString("convoy_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Try to stay close to it! ähnelt.
        /// </summary>
        internal static string convoy_intro_2 {
            get {
                return ResourceManager.GetString("convoy_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A blue dot on the map shows its position. ähnelt.
        /// </summary>
        internal static string convoy_intro_3 {
            get {
                return ResourceManager.GetString("convoy_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ~r~Don&apos;t lose the other truck! ähnelt.
        /// </summary>
        internal static string convoy_warning {
            get {
                return ResourceManager.GetString("convoy_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task {0}/{1} ähnelt.
        /// </summary>
        internal static string current_task_notification {
            get {
                return ResourceManager.GetString("current_task_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ~r~debug mode: ~b~{0} ähnelt.
        /// </summary>
        internal static string debug_mode_active {
            get {
                return ResourceManager.GetString("debug_mode_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desert Initialization ähnelt.
        /// </summary>
        internal static string desert_initialization {
            get {
                return ResourceManager.GetString("desert_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this task you drive a motorcycle. ähnelt.
        /// </summary>
        internal static string desert_intro_1 {
            get {
                return ResourceManager.GetString("desert_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are 2 possible routes. ähnelt.
        /// </summary>
        internal static string desert_intro_2 {
            get {
                return ResourceManager.GetString("desert_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The normal route leads over roads and the highway ähnelt.
        /// </summary>
        internal static string desert_intro_3 {
            get {
                return ResourceManager.GetString("desert_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The alternative route leads through the desert. ähnelt.
        /// </summary>
        internal static string desert_intro_4 {
            get {
                return ResourceManager.GetString("desert_intro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The latter is marked by red checkpoints. ähnelt.
        /// </summary>
        internal static string desert_intro_5 {
            get {
                return ResourceManager.GetString("desert_intro_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How far is the player away from the leading convoy vehicle. ähnelt.
        /// </summary>
        internal static string distance {
            get {
                return ResourceManager.GetString("distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How far away was the leading vehicle from its target when player reached the last checkpoint ähnelt.
        /// </summary>
        internal static string distance_leader_target {
            get {
                return ResourceManager.GetString("distance_leader_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long did the player drive against traffic ähnelt.
        /// </summary>
        internal static string duration_against_traffic {
            get {
                return ResourceManager.GetString("duration_against_traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long was the brake pedal applied overall ähnelt.
        /// </summary>
        internal static string duration_brake {
            get {
                return ResourceManager.GetString("duration_brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long was the handbrake applied overall ähnelt.
        /// </summary>
        internal static string duration_handbrake {
            get {
                return ResourceManager.GetString("duration_handbrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long did the player drive on pavement ähnelt.
        /// </summary>
        internal static string duration_on_pavement {
            get {
                return ResourceManager.GetString("duration_on_pavement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long was the player in front of the leading vehicle ähnelt.
        /// </summary>
        internal static string duration_player_leads {
            get {
                return ResourceManager.GetString("duration_player_leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use WASD and mouse to move ähnelt.
        /// </summary>
        internal static string exploration_move {
            get {
                return ResourceManager.GetString("exploration_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signal received from gas pedal ähnelt.
        /// </summary>
        internal static string gas {
            get {
                return ResourceManager.GetString("gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tasks last from 1 to about 3min. ähnelt.
        /// </summary>
        internal static string intro_5_1 {
            get {
                return ResourceManager.GetString("intro_5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GTA V is an open world action game. ähnelt.
        /// </summary>
        internal static string intro1 {
            get {
                return ResourceManager.GetString("intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This might result in hostile action from bystanders ... ähnelt.
        /// </summary>
        internal static string intro10 {
            get {
                return ResourceManager.GetString("intro10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or persecution by the police. ähnelt.
        /// </summary>
        internal static string intro11 {
            get {
                return ResourceManager.GetString("intro11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your wanted level is shown on the top right of the screen. ähnelt.
        /// </summary>
        internal static string intro12 {
            get {
                return ResourceManager.GetString("intro12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Higher wanted level = more police ähnelt.
        /// </summary>
        internal static string intro13 {
            get {
                return ResourceManager.GetString("intro13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collisions will damage your car. ähnelt.
        /// </summary>
        internal static string intro14 {
            get {
                return ResourceManager.GetString("intro14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the car&apos;s hitpoints drop to 0, it will explode. ähnelt.
        /// </summary>
        internal static string intro15 {
            get {
                return ResourceManager.GetString("intro15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the character&apos;s hitpoints drop to 0, he will fall unconscious. ähnelt.
        /// </summary>
        internal static string intro16 {
            get {
                return ResourceManager.GetString("intro16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The car is controlled with the steering wheel and gas/brake pedal. ähnelt.
        /// </summary>
        internal static string intro17 {
            get {
                return ResourceManager.GetString("intro17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no blinkers. Just turn. ähnelt.
        /// </summary>
        internal static string intro18 {
            get {
                return ResourceManager.GetString("intro18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To reverse, stand on the brake pedal after the car has stopped ähnelt.
        /// </summary>
        internal static string intro19 {
            get {
                return ResourceManager.GetString("intro19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This study focusses on the singleplayer mode of the game. ähnelt.
        /// </summary>
        internal static string intro2 {
            get {
                return ResourceManager.GetString("intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hold the steering wheel turned to flip the car back over. ähnelt.
        /// </summary>
        internal static string intro20 {
            get {
                return ResourceManager.GetString("intro20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You now have 10min. to get familiar with the game. ähnelt.
        /// </summary>
        internal static string intro21 {
            get {
                return ResourceManager.GetString("intro21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can drive wherever you want. ähnelt.
        /// </summary>
        internal static string intro22 {
            get {
                return ResourceManager.GetString("intro22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To start immediately, drive through the checkpoints. ähnelt.
        /// </summary>
        internal static string intro23 {
            get {
                return ResourceManager.GetString("intro23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You control one of these three player characters. ähnelt.
        /// </summary>
        internal static string intro3 {
            get {
                return ResourceManager.GetString("intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All of the tasks revolve around a driving task. ähnelt.
        /// </summary>
        internal static string intro4 {
            get {
                return ResourceManager.GetString("intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will spend most of the time in a car. ähnelt.
        /// </summary>
        internal static string intro5 {
            get {
                return ResourceManager.GetString("intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive through these checkpoints. ähnelt.
        /// </summary>
        internal static string intro6 {
            get {
                return ResourceManager.GetString("intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The route is displayed on the minimap. ähnelt.
        /// </summary>
        internal static string intro7 {
            get {
                return ResourceManager.GetString("intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can either adhere to the traffic rules or ignore them. ähnelt.
        /// </summary>
        internal static string intro8 {
            get {
                return ResourceManager.GetString("intro8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is possible to run over pedestrians. ähnelt.
        /// </summary>
        internal static string intro9 {
            get {
                return ResourceManager.GetString("intro9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language selected:  ähnelt.
        /// </summary>
        internal static string language_selected {
            get {
                return ResourceManager.GetString("language_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This was the last task! ähnelt.
        /// </summary>
        internal static string last_race {
            get {
                return ResourceManager.GetString("last_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum speed of the player&apos;s vehicle (possibly in m/s) ähnelt.
        /// </summary>
        internal static string maximum_speed {
            get {
                return ResourceManager.GetString("maximum_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        internal static string menu_english {
            get {
                return ResourceManager.GetString("menu_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        internal static string menu_german {
            get {
                return ResourceManager.GetString("menu_german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available languages ähnelt.
        /// </summary>
        internal static string menu_languages {
            get {
                return ResourceManager.GetString("menu_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This can&apos;t be done during tasks. ähnelt.
        /// </summary>
        internal static string menu_not_during_task {
            get {
                return ResourceManager.GetString("menu_not_during_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate Cam Designer? ähnelt.
        /// </summary>
        internal static string menu_toggle_cam_designer {
            get {
                return ResourceManager.GetString("menu_toggle_cam_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle debug mode? ähnelt.
        /// </summary>
        internal static string menu_toggle_debug {
            get {
                return ResourceManager.GetString("menu_toggle_debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle route designer? ähnelt.
        /// </summary>
        internal static string menu_toggle_route_designer {
            get {
                return ResourceManager.GetString("menu_toggle_route_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle the traffic light manager ähnelt.
        /// </summary>
        internal static string menu_toggle_tl_mgr {
            get {
                return ResourceManager.GetString("menu_toggle_tl_mgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No settings were found in the configuration file. ähnelt.
        /// </summary>
        internal static string no_settings {
            get {
                return ResourceManager.GetString("no_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file &quot;App.config&quot; could not be opened. ähnelt.
        /// </summary>
        internal static string no_settings_file {
            get {
                return ResourceManager.GetString("no_settings_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No key &apos;AppSettings&apos; was found in App.config ähnelt.
        /// </summary>
        internal static string no_settings_key {
            get {
                return ResourceManager.GetString("no_settings_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When was the garbage truck visible to the player ähnelt.
        /// </summary>
        internal static string obstacle_visible {
            get {
                return ResourceManager.GetString("obstacle_visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times did the player collide with pedestrians ähnelt.
        /// </summary>
        internal static string pedestrian_collisions {
            get {
                return ResourceManager.GetString("pedestrian_collisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many hitpoints did the player&apos;s character have after the task ähnelt.
        /// </summary>
        internal static string player_health {
            get {
                return ResourceManager.GetString("player_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did the player drive past the garbage truck ähnelt.
        /// </summary>
        internal static string player_passed_garbage_truck {
            get {
                return ResourceManager.GetString("player_passed_garbage_truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How far away were nearby vehicles on average ähnelt.
        /// </summary>
        internal static string possible_vc_mean_distance {
            get {
                return ResourceManager.GetString("possible_vc_mean_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many cars were in a radius around the player, providing the possibility for collision ähnelt.
        /// </summary>
        internal static string possible_vehicle_collisions {
            get {
                return ResourceManager.GetString("possible_vehicle_collisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task finished! - Time: {0}s ähnelt.
        /// </summary>
        internal static string race_finished {
            get {
                return ResourceManager.GetString("race_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started task {0}/{1} ähnelt.
        /// </summary>
        internal static string race_started {
            get {
                return ResourceManager.GetString("race_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All races are set up. ähnelt.
        /// </summary>
        internal static string racessetup {
            get {
                return ResourceManager.GetString("racessetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your car is placed on the road in: {0} ähnelt.
        /// </summary>
        internal static string reset_warning {
            get {
                return ResourceManager.GetString("reset_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Times player was reset after being lost. ähnelt.
        /// </summary>
        internal static string resets {
            get {
                return ResourceManager.GetString("resets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ~r~route designer active: ~b~{0} ähnelt.
        /// </summary>
        internal static string route_designer_active {
            get {
                return ResourceManager.GetString("route_designer_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die press Y to add an alternative waypoint ähnelt.
        /// </summary>
        internal static string route_designer_alt_cp {
            get {
                return ResourceManager.GetString("route_designer_alt_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no checkpoint to add an alternative to! ähnelt.
        /// </summary>
        internal static string route_designer_no_cp {
            get {
                return ResourceManager.GetString("route_designer_no_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die press X to toggle a waypoint ähnelt.
        /// </summary>
        internal static string route_designer_reg_cp {
            get {
                return ResourceManager.GetString("route_designer_reg_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternative checkpoint removed ähnelt.
        /// </summary>
        internal static string route_designer_rm_alt_cp {
            get {
                return ResourceManager.GetString("route_designer_rm_alt_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checkpoint removed ähnelt.
        /// </summary>
        internal static string route_designer_rm_cp {
            get {
                return ResourceManager.GetString("route_designer_rm_cp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Velocity of the player&apos;s car ähnelt.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press [F10] to start first race ähnelt.
        /// </summary>
        internal static string startracepromp {
            get {
                return ResourceManager.GetString("startracepromp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input of the steering wheel ähnelt.
        /// </summary>
        internal static string steering {
            get {
                return ResourceManager.GetString("steering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suburban Initialization ähnelt.
        /// </summary>
        internal static string suburban_initialization {
            get {
                return ResourceManager.GetString("suburban_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This task will be a short drive through the neighbourhood. ähnelt.
        /// </summary>
        internal static string suburban_intro_1 {
            get {
                return ResourceManager.GetString("suburban_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The streets might be busy with cars. ähnelt.
        /// </summary>
        internal static string suburban_intro_2 {
            get {
                return ResourceManager.GetString("suburban_intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your car is rather fast, despite looks. ähnelt.
        /// </summary>
        internal static string suburban_intro_3 {
            get {
                return ResourceManager.GetString("suburban_intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The GameTime the task was finished at ähnelt.
        /// </summary>
        internal static string task_end_time {
            get {
                return ResourceManager.GetString("task_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The GameTime the task started at ähnelt.
        /// </summary>
        internal static string task_start_time {
            get {
                return ResourceManager.GetString("task_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The task has started! ähnelt.
        /// </summary>
        internal static string task_started {
            get {
                return ResourceManager.GetString("task_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long it took the player to finish the task ähnelt.
        /// </summary>
        internal static string task_total_time {
            get {
                return ResourceManager.GetString("task_total_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is an alternative route later on. ähnelt.
        /// </summary>
        internal static string terminal_intro_1 {
            get {
                return ResourceManager.GetString("terminal_intro_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times did the player drive against traffic ähnelt.
        /// </summary>
        internal static string times_against_traffic {
            get {
                return ResourceManager.GetString("times_against_traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times was the brake pressed ähnelt.
        /// </summary>
        internal static string times_braked {
            get {
                return ResourceManager.GetString("times_braked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times was the handbrake used ähnelt.
        /// </summary>
        internal static string times_handbraked {
            get {
                return ResourceManager.GetString("times_handbraked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times did the player drive on the pavement ähnelt.
        /// </summary>
        internal static string times_on_pavement {
            get {
                return ResourceManager.GetString("times_on_pavement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times did player take over the leading vehicle ähnelt.
        /// </summary>
        internal static string times_player_leads {
            get {
                return ResourceManager.GetString("times_player_leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traffic light manager active: {0} ähnelt.
        /// </summary>
        internal static string tl_mgr_active {
            get {
                return ResourceManager.GetString("tl_mgr_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times was the player&apos;s vehicle upside down ähnelt.
        /// </summary>
        internal static string upside_down {
            get {
                return ResourceManager.GetString("upside_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How many times did the player collide with other vehicles ähnelt.
        /// </summary>
        internal static string vehicle_collisions {
            get {
                return ResourceManager.GetString("vehicle_collisions", resourceCulture);
            }
        }
    }
}
