//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModForResearchTUB.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModForResearchTUB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GTA V is an open world action game. ähnelt.
        /// </summary>
        internal static string intro1 {
            get {
                return ResourceManager.GetString("intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This might result in hostile action from bystanders ... ähnelt.
        /// </summary>
        internal static string intro10 {
            get {
                return ResourceManager.GetString("intro10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die or persecution by the police. ähnelt.
        /// </summary>
        internal static string intro11 {
            get {
                return ResourceManager.GetString("intro11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your wanted level is shown on the top right of the screen. ähnelt.
        /// </summary>
        internal static string intro12 {
            get {
                return ResourceManager.GetString("intro12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Higher wanted level = more police ähnelt.
        /// </summary>
        internal static string intro13 {
            get {
                return ResourceManager.GetString("intro13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collisions will damage your car. ähnelt.
        /// </summary>
        internal static string intro14 {
            get {
                return ResourceManager.GetString("intro14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the car&apos;s hitpoints drop to 0, it will explode. ähnelt.
        /// </summary>
        internal static string intro15 {
            get {
                return ResourceManager.GetString("intro15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When the character&apos;s hitpoints drop to 0, he will fall unconscious. ähnelt.
        /// </summary>
        internal static string intro16 {
            get {
                return ResourceManager.GetString("intro16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This study focusses on the singleplayer mode of the game. ähnelt.
        /// </summary>
        internal static string intro2 {
            get {
                return ResourceManager.GetString("intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You control one of these three player characters. ähnelt.
        /// </summary>
        internal static string intro3 {
            get {
                return ResourceManager.GetString("intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All of the tests revolve around a driving task. ähnelt.
        /// </summary>
        internal static string intro4 {
            get {
                return ResourceManager.GetString("intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You will spend most of the time in a car. ähnelt.
        /// </summary>
        internal static string intro5 {
            get {
                return ResourceManager.GetString("intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive through these checkpoints. ähnelt.
        /// </summary>
        internal static string intro6 {
            get {
                return ResourceManager.GetString("intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The route is displayed on the minimap. ähnelt.
        /// </summary>
        internal static string intro7 {
            get {
                return ResourceManager.GetString("intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can either adhere to the traffic rules or ignore them. ähnelt.
        /// </summary>
        internal static string intro8 {
            get {
                return ResourceManager.GetString("intro8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is possible to run over pedestrians. ähnelt.
        /// </summary>
        internal static string intro9 {
            get {
                return ResourceManager.GetString("intro9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All races are set up. ähnelt.
        /// </summary>
        internal static string racessetup {
            get {
                return ResourceManager.GetString("racessetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press [F10] to start first race ähnelt.
        /// </summary>
        internal static string startracepromp {
            get {
                return ResourceManager.GetString("startracepromp", resourceCulture);
            }
        }
    }
}
